name: path
description: A simple command-line application.
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path_dependency:
    path: ../path_dependency

dev_dependencies:
  path_dev_dependency:
    path: ../path_dev_dependency
